# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kconnect < Formula
  desc "Kubernetes Connection Manager CLI"
  homepage "https://github.com/fidelity/kconnect"
  version "0.5.17-rc.1"

  depends_on "Azure/kubelogin/kubelogin"
  depends_on "aws-iam-authenticator"
  depends_on "kubernetes-cli"

  on_macos do
    on_intel do
      url "https://github.com/fidelity/kconnect/releases/download/0.5.17-rc.1/kconnect_macos_amd64.tar.gz"
      sha256 "54cb5fa55089b5bf685f2ebd5c635c436b8fbd99a3c88428e728c01dc85edf54"

      def install
        bin.install "kconnect"
      end
    end
    on_arm do
      url "https://github.com/fidelity/kconnect/releases/download/0.5.17-rc.1/kconnect_macos_arm64.tar.gz"
      sha256 "4ae8ee9621fc3ba7dfce6fa8db0d4612f50005b4a8e2c94ba54a285c11a9671b"

      def install
        bin.install "kconnect"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/fidelity/kconnect/releases/download/0.5.17-rc.1/kconnect_linux_amd64.tar.gz"
        sha256 "02ae1eb3bafb091b5b0d474ef4ba70e889888158b41a191f33cf551aa8900a96"

        def install
          bin.install "kconnect"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/fidelity/kconnect/releases/download/0.5.17-rc.1/kconnect_linux_arm64.tar.gz"
        sha256 "2adda9f3eb9eb0178d607e58f92da198affe9f9dba1b737053605f65d2d8d7db"

        def install
          bin.install "kconnect"
        end
      end
    end
  end
end
