# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kconnect < Formula
  desc "Kubernetes Connection Manager CLI"
  homepage "https://github.com/fidelity/kconnect"
  version "0.5.21-rc.1"

  depends_on "Azure/kubelogin/kubelogin"
  depends_on "aws-iam-authenticator"
  depends_on "kubernetes-cli"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fidelity/kconnect/releases/download/0.5.21-rc.1/kconnect_macos_amd64.tar.gz"
      sha256 "7d29140912d8bcb149a339706d0abd519d2598ddefa6b869b36a093e140900a7"

      def install
        bin.install "kconnect"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fidelity/kconnect/releases/download/0.5.21-rc.1/kconnect_macos_arm64.tar.gz"
      sha256 "dfea6bfc0bc5793cf83a215e5d08ca724aa814b285da60a6556d1e9e77cc8db2"

      def install
        bin.install "kconnect"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fidelity/kconnect/releases/download/0.5.21-rc.1/kconnect_linux_amd64.tar.gz"
      sha256 "c19fb53fd0b9cea89c5d01ac6f05aad4b54034d62b13fecd2d153943e508f3ee"
      def install
        bin.install "kconnect"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fidelity/kconnect/releases/download/0.5.21-rc.1/kconnect_linux_arm64.tar.gz"
      sha256 "48a77127474506eb6fe339c392a2ab97c0df1138cace700de1f212c89b2c937d"
      def install
        bin.install "kconnect"
      end
    end
  end
end
