# This file was generated by GoReleaser. DO NOT EDIT.
class Kconnect < Formula
  desc "The Kubernetes Connection Manager CLI"
  homepage "https://github.com/fidelity/kconnect"
  version "0.1.0-rc.3"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/fidelity/kconnect/releases/download/0.1.0-rc.3/kconnect_macos_64-bit.tar.gz"
    sha256 "ce873dd995271cb23556814156d6168688ef688f26bb5e4ce473d5f2fa897c2f"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/fidelity/kconnect/releases/download/0.1.0-rc.3/kconnect_linux_64-bit.tar.gz"
      sha256 "ef69ae3c1059e965267a89e98ca754e3c17fb535f152e1cc5b12f224b31daa7e"
    end
  end
  
  depends_on "kubernetes-cli"
  depends_on "aws-iam-authenticator"

  def install
    bin.install "kconnect"
  end
end
