name: brew test-bot
on:
  push:
    branches: master
  pull_request: []
jobs:
  test-bot:
    runs-on: macos-latest
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@main
        with:
          test-bot: true
      - name: Run brew test-bot
        run: brew test-bot
